# Generated by Django 4.1.3 on 2022-11-15 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_commentpost_dislikes_commentpost_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='social.commentpost'),
        ),
    ]
