# Generated by Django 4.1.3 on 2022-11-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
