# Generated by Django 4.1.3 on 2022-11-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_tag_comment_tags_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='images', to='social.image'),
        ),
    ]
