# Generated by Django 4.1.3 on 2023-01-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_alter_userprofile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('COMMENT', 'Comment'), ('FOLLOW', 'Follow'), ('DM', 'DM')], default='LIKE', max_length=20),
            preserve_default=False,
        ),
    ]
